<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1629685674079' stop='1629685795383'>
    <name>verify log project append funtion</name>
    <title>verify log project append funtion</title>
    <test-cases>
        <test-case start='1629685674079' status='failed' stop='1629685675415'>
            <name>Qick append verify add new line</name>
            <title>Qick append verify add new line</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='17988246-e03d-414a-a6c3-d836dc9d6e53-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>Failed: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/projects" routerlinkactive="active">...&lt;/a> is not clickable at point (720, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)</message>
                <stack-trace>WebDriverError: element click intercepted: Element &lt;a _ngcontent-goi-c1="" class="nav-link" href="/projects" routerlinkactive="active">...&lt;/a> is not clickable at point (720, 30). Other element would receive the click: &lt;div _ngcontent-goi-c8="" class="modal">...&lt;/div>
                  (Session info: headless chrome=92.0.4515.159)
                  (Driver info: chromedriver=92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}),platform=Windows NT 10.0.19043 x86_64)
                    at Object.checkLegacyResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\http.js:441:30
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: WebElement.click()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at WebElement.schedule_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
                    at WebElement.click (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
                    at actionFn (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:89:44)
                    at Array.map (&lt;anonymous>)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:461:65
                    at ManagedPromise.invokeCallback_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2927:27Error: 
                    at ElementArrayFinder.applyAction_ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\element.js:831:22)
                    at Function.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\utils\function-util.ts:127:15)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\tslib\tslib.js:112:62)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: Run it("Qick append verify add new line") in control flow
                    at UserContext.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\node_modules\jasminewd2\index.js:94:19)
                    at attempt (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
                    at E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
                    at E:\vmware\Loop\GitHub\e2e\node_modules\jasminewd2\index.js:64:48
                    at ControlFlow.emit (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\events.js:62:21)
                    at ControlFlow.shutdown_ (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2674:10)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\promise.js:2599:53
                From asynchronous test: 
                Error: 
                    at Suite.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\features\append-project-log-spec.ts:14:3)
                    at addSpecsToSuite (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\features\append-project-log-spec.ts:10:1)
                    at Module._compile (node:internal/modules/cjs/loader:1101:14)
                    at Module.m._compile (E:\vmware\Loop\GitHub\e2e\node_modules\ts-node\src\index.ts:422:23)
                    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
                    at Object.require.extensions.&lt;computed> [as .ts] (E:\vmware\Loop\GitHub\e2e\node_modules\ts-node\src\index.ts:425:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629685675415' status='failed' stop='1629685795259'>
            <name>Qick append verify delete new line</name>
            <title>Qick append verify delete new line</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='0b153e06-519c-44ad-80e9-d8490d6ebe65-attachment.png' type='image/png' size='66354'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629685795261' status='failed' stop='1629685795316'>
            <name>Qick append verify upload sigle log file and publish</name>
            <title>Qick append verify upload sigle log file and publish</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:63150</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:63150
                    at ClientRequest.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (node:events:394:28)
                    at Socket.socketErrorListener (node:_http_client:447:9)
                    at Socket.emit (node:events:394:28)
                    at emitErrorNT (node:internal/streams/destroy:157:8)
                    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
                    at processTicksAndRejections (node:internal/process/task_queues:83:21)
                From: Task: WebDriver.manage().logs().get(browser)
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at Logs.get (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:1731:25)
                    at Jasmine2Reporter._callee7$ (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:5154:64)
                    at tryCatch (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:5748:40)
                    at Generator.invoke [as _invoke] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:6022:22)
                    at Generator.prototype.&lt;computed> [as next] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:5781:21)
                    at step (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:4754:191)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:4754:361
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                From: Task: Run beforeEach in control flow
                    at UserContext.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\node_modules\jasminewd2\index.js:94:19)
                    at attempt (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
                    at Spec.execute (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
                    at UserContext.fn (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
                    at attempt (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                From asynchronous test: 
                Error: 
                    at Jasmine2Reporter.jasmineStarted (E:\vmware\Loop\GitHub\e2e\node_modules\protractor-beautiful-reporter\index.js:4948:13)
                    at dispatch (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4366:28)
                    at ReportDispatcher.jasmineStarted (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4337:11)
                    at Env.execute (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:975:16)
                    at Jasmine.execute (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\lib\jasmine.js:200:12)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\frameworks\jasmine.js:132:15
                    at Function.promise (E:\vmware\Loop\GitHub\e2e\node_modules\q\q.js:682:9)
                    at E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\frameworks\jasmine.js:104:14
                    at _fulfilled (E:\vmware\Loop\GitHub\e2e\node_modules\q\q.js:834:54)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1629685795316' status='failed' stop='1629685795380'>
            <name>File append verify selete existing log file</name>
            <title>File append verify selete existing log file</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:63150</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:63150
                    at ClientRequest.&lt;anonymous> (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (node:events:394:28)
                    at Socket.socketErrorListener (node:_http_client:447:9)
                    at Socket.emit (node:events:394:28)
                    at emitErrorNT (node:internal/streams/destroy:157:8)
                    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
                    at processTicksAndRejections (node:internal/process/task_queues:83:21)
                From: Task: WebDriver.takeScreenshot()
                    at Driver.schedule (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at Driver.takeScreenshot (E:\vmware\Loop\GitHub\e2e\node_modules\selenium-webdriver\lib\webdriver.js:1085:17)
                    at run (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\browser.js:58:33)
                    at ProtractorBrowser.to.&lt;computed> [as takeScreenshot] (E:\vmware\Loop\GitHub\e2e\node_modules\protractor\built\browser.js:66:16)
                    at Spec.jasmine.Spec.addExpectationResult (E:\vmware\Loop\GitHub\e2e\protractor.config.js:147:17)
                    at Spec.onException (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:548:10)
                    at QueueRunner.onException (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:515:50)
                    at onException (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4310:14)
                    at handleError (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4243:11)
                    at process.onerror (E:\vmware\Loop\GitHub\e2e\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2371:17)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>